### ISSUE TITLE
Feature Request average Backupsize

### ISSUE THREAD

**Issue by Lucadrio** [davidedg/check_mk_plugins#1]
Hello,

This is a feature Request for your Veeam-Plugin. It would be useful to get an average Backupsize Value. With this value you could have a check if your Backupsize increased unintended.

_For Example:_

Your average Backupsize is about 33 GB big and suddenly it backed up 40 GB. Then you could get notified and check whether it is intended or if there is something fishy (malware e.g.).

Never the less your Check_MK Agent Plugin is not compatible with the Agent Bakery in the Check_MK Version: Enterprise 1.2.8p15.
 
Cheers,
Luca

**Comment by davidedg** [comment]
I just developed the agent-side plugin, not the server-side (developed by CheckMK).
So I cannot insert any new features that should depend on server-side.
